motivate = (
"Bravo ! Tes jambes vont te remercier pour cet effort impressionnant.",
"Tu viens de repousser tes limites, continue comme ça !",
"Tes muscles travaillent fort, et ça se voit. Félicitations !",
"Chaque squat te rapproche un peu plus de tes objectifs. Ne lâche rien !",
"La douleur d'aujourd'hui est la force de demain. Tu es sur la bonne voie !",
"Tu as juste défié la gravité avec ces squats. Continue à voler haut !",
"Squatter avec autant de détermination, c'est la clé du succès. Continue comme ça !",
"Les squats ne sont pas faciles, mais tu les rends impressionnants. Bravo !",
"Chaque série de squats te rapproche un peu plus de la version la plus forte de toi-même. Continue cette belle progression !",
"Ton boule il chamboule", 
"Bravo mon reuf",
"C'est tout ? Tu peux faire mieux",
"Tu es sur la bonne voie, la voie du boule rebondi",
"Ces squats ? C'est un échauffement pour toi, non ?",
"Les squats ne te font même pas transpirer, c'est mignon.",
"Les jambes en feu ? Pour toi, c'est juste une sensation de chaleur agréable, non ?",
"Les squats sont ton café du matin, avoue !",
"Ces squats étaient tellement faciles que même la gravité était impressionnée.",
"Squatter avec style, comme d'habitude. Quelle surprise !",
"Les squats, c'est ton hobby ou tu les fais juste pour montrer aux autres comment c'est fait ?",
"Les squats te font rire, avoue. C'est ça qui explique ce sourire, non ?",
"Quand les squats deviennent faciles, c'est le signe que tu es prête pour un nouveau défi, non ?",
"Squats parfaits, comme d'habitude. Quand est-ce que tu nous montres quelque chose de difficile ?",
"Ces squats étaient un peu trop simples, non ? On dirait que tu t'ennuies là-dedans.",
"Les squats pour toi, c'est comme une pause détente. Pas vrai ?",
"Il est con ce défi non ?",
"C'est ton boule qui rebondit ou les squats deviennent plus faciles ?",



"Allez là!",
"Un petit squat pour l’homme, un gros boule pour l’humanité",
"Tous pour boule, boule pour tous !",
"Tu es sûr d'avoir tout donner ? Encore un effort !",
"Mais tu serais pas boulemique toi ?",
"Ce coup de boule est digne de Zizou !",
"Ton boule me chamboule",
"Ton choule bamboule",
"Harder, better, faster, stronger !",
"Ton ass'encion est fulgurante !",
"Objectif 30 000 en 2025 ?",
"Les squats c’est bon, maintenant les pompes",
"Ton boule est assthetique"
)
